### ISSUE TITLE
Can't find System.Threading.Thread.Dataflow

### ISSUE THREAD

**Issue by DrMistry** [lecode-official/gphoto2-dotnet#1]
Which version of Mono/Monodevelop did you use for this project?  I have the latest build from the Mono repository installed on my Pi and System.Threading.Thread.Dataflow is not available and without any build instructions this renders your work unusable for me!

**Comment by lecode-official** [comment]
This project is using the `mono-complete` package, which should contain the `System.Threading.Thread.Dataflow` API. You can install the `mono-complete` package via

``` bash
sudo apt-get install mono-complete
```

Other than that the project only depends on gPhoto2, which can be installed using the following command:

``` bash
sudo apt-get install gphoto2
```

The [README.md](https://github.com/lecode-official/gphoto2-dotnet/blob/master/README.md) file now contains some more detailed instruction on how to use the library.

Unfortunately the project is not yet ready to be used in a production environment. I hope to release a usable version soon.
